app:
  server: 10.147.20.25:3306
  database: tsa.agencia.migracion
  user: root
  password: root
  add-properties: true
  logging: debug
  livereload:
    enabled: true
    port: 35980
  open-in-view: true
  ftp-host: 119.8.73.151
  ftp-user: ftp-agencia
  ftp-password: Agn123321Ines
  hours-offset: 1
  local-path: /data/temp/


spring:
  datasource:
    url: jdbc:mysql://${app.server}/${app.database}?useSSL=false&serverTimezone=UTC
    username: ${app.user}
    password: ${app.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: ${app.open-in-view}
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: ${app.livereload.enabled}
      port: ${app.livereload.port}
    add-properties: ${app.add-properties}
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    eterea.api.rest: DEBUG
    web: ${app.logging}
    org:
      hibernate:
        SQL: ${app.logging}

