sequenceDiagram
    participant ON_WebService as OrderNoteWebService
    participant WP_API as API de WordPress
    participant Logger as SistemaDeLogs
    participant ON_Service as OrderNoteService

    ON_WebService->>+WP_API: GET /wp-json/wc/v3/orders
    
    alt Falla en la API de WordPress
        WP_API-->>-ON_WebService: 500 Internal Server Error
        ON_WebService->>+Logger: log.error("Error al obtener datos de WordPress: 500")
        Logger-->>-ON_WebService: Log registrado
        ON_WebService-xON_Service: Lanza OrderNoteException("Fallo la importación")
    end
