sequenceDiagram
    participant Cliente
    participant API
    participant ServicioOrderNote
    participant RepositorioOrderNote

    Cliente->>API: GET /documento/last/{numeroDocumento}/importe/{importe}
    API->>ServicioOrderNote: findLastByNumeroDocumentoAndImporte
    ServicioOrderNote->>RepositorioOrderNote: findTopByBillingDniPasaporteContainsAndOrderTotalOrderByOrderNumberIdDesc
    RepositorioOrderNote-->>ServicioOrderNote: OrderNote
    ServicioOrderNote-->>API: OrderNote
    API-->>Cliente: OrderNote (JSON)
