name: Despliegue de Documentación ETEREA.import-service

on:
  schedule:
    - cron: '0 0 * * *'  # Actualización diaria de la documentación
  workflow_dispatch:      # Permite actualizar manualmente
  push:
    branches: [ "main" ]  # Solo en la rama principal
  issues:
    types: [opened, closed, edited, deleted]
  milestone:
    types: [created, closed, edited, deleted]

# Corregimos la sintaxis de los permisos
permissions:
  contents: write    # Para repo y documentación
  pages: write      # Para GitHub Pages
  id-token: write   # Para autenticación
  issues: read      # Para leer issues
  pull-requests: write  # Para PR y merge
  repository-projects: write
  actions: read     # Para acceder a las acciones
  deployments: write    # Para despliegues
  statuses: write   # Para actualizar estados

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCS_BRANCH: gh-pages
  DOCS_FOLDER: docs

jobs:
  build:
    name: Construir Documentación
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub markdown2 jinja2 requests

      - name: Obtener Documentación de API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/fetch_github_data.py

      - name: Generar Documentación de API
        run: |
          python scripts/generate_docs.py

      - name: Generar Wiki Técnica
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          python scripts/generate_wiki.py
      
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Construir con Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      
      - name: Subir Artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      
  deploy:
    name: Desplegar Documentación
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar Documentación en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 